filetype off
set runtimepath+=./vader.vim/
set runtimepath+=./vim-fugitive/
set runtimepath+=./fugitive-cgit.vim
set runtimepath+=../vader.vim/
set runtimepath+=../vim-fugitive/
set runtimepath+=../fugitive-cgit.vim
filetype plugin indent on
syntax enable
set nomore
set noswapfile
set viminfo=
